name: dottie_inspector
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
#  intro_slider: ^2.3.1
#  nice_intro: ^0.1.4
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^2.0.15
  http: ^0.13.4
  fluttertoast: ^8.0.8
  intl: ^0.15.8
  percent_indicator: ^2.1.5
  url_launcher: ^5.1.2
#  keyboard_visibility: ^0.5.6
  contacts_service: ^0.4.3
  permission_handler: ^9.1.0
  flutter_slidable: ^0.5.5
  validators: ^2.0.1
  carousel_slider: ^3.0.0
  image_picker: ^0.8.4+9
  path_provider: ^2.0.9
  path: ^1.6.0
  flutter_html: ^0.11.1
#  connectivity: ^0.4.3+7
  progress_hud: ^1.1.0
  geolocator: ^8.2.0
#  firebase_dynamic_links: ^4.3.9
  dotted_border: ^2.0.0+2
  path_drawing: ^1.0.0

  flutter_appavailability: ^0.0.21
#  search_map_place: ^0.3.0
#  mapbox_search:
# // mapbox_search_flutter:
#  mapbox_gl:
#  mapbox_geocoding:
#  mapbox_gl:
#    git:
#      url: https://github.com/tobrun/flutter-mapbox-gl.git

  signature: ^5.0.0
  drag_and_drop_lists: ^0.2.7
  hand_signature: ^0.6.3
  reorderables: ^0.3.2
  image: ^3.1.3
  flutter_native_image: ^0.0.5+3

  modal_progress_hud: ^0.1.3
  image_editor: ^1.0.2
  firebase_crashlytics: ^2.5.3
  firebase_core : ^1.13.1
  firebase_analytics: ^9.1.2
#  bugsnag_crashlytics: ^0.0.7
  flutter_svg: ^1.0.3
  image_cropper: ^1.4.1
  image_cropper_platform_interface: ^3.0.3
  connectivity_plus: ^2.3.0
  sqflite:
#  flutter_background_service: ^0.1.5
#  flutter_plugin_android_lifecycle: ^1.0.4
#  workmanager: ^0.5.0
#  gallery_saver: ^2.0.3
#  background_fetch: 1.0.3
#  background_fetch:
#    git:
#      url: https://github.com/transistorsoft/flutter_background_fetch

#  cached_network_image: ^2.5.1
  synchronized: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  bottom_picker: ^1.9.1
  gleap_sdk: ^6.4.8
  package_info_plus: ^2.0.0
  provider: ^6.0.4
#  page_transition: ^2.0.9
#  flutter_local_notifications: ^9.3.2
#  in_app_purchase: ^3.0.1
#  instabug_flutter:
#  gradient_borders: ^0.2.0
#  test: ^1.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  lint: ^1.5.3

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
#  adaptive_icon_background: "assets/launcher/white-splash.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/intro1/
    - assets/intro1/intro_1.png
    - assets/vessel/
    - assets/welcome/
    - assets/complete_inspection/
    - assets/boolean/
    - assets/settings/
    - assets/subscription/
    - assets/new_ui/
    - assets/index/
    - assets/shape/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: WorkSans
#      fonts:
#        - asset: assets/font/WorkSans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
